config/routes.rb
BillsWithFriends::Application.routes.draw do
  devise_for :users

  resources :users

  resources :registers

  resources :you_owe_mes

  resources :payments

  resources :expenses

  root :to => "home#index"

  match '/summary', :to => 'summary#index'

  match '/ledger', :to => 'ledger#index'

  match '/registers/:id/audit', :to => "registers#audit", :as => "audit_register"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

end

app/models/register.rb
class Register < ActiveRecord::Base
	after_initialize :default_values

	has_one :user

	validates_presence_of :creditor_id, :debtor_id, :credit_extended
	validates :credit_extended, :numericality => {:greater_than_or_equal_to => 0}

	def self.current_user_owns (current_user_id)
		where(:creditor_id => current_user_id)
	end

	def self.current_user_owes (current_user_id)
		where(:debtor_id => current_user_id)
	end

	def self.register_for_payment (creditor_id, debtor_id)
		where(:creditor_id => creditor_id, :debtor_id => debtor_id)
	end

	private
	    def default_values
	      self.credit_extended ||= "0"
	    end
end

# fat model skinny controller
#you're gonna put the book keeping code in a model, or possibly a module under lib/
#the controller is just going to call that method populating an instance variable.. and then the view displays it

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /registers
  # GET /registers.json
  def index
    @owes_user = Register.current_user_owns(current_user.id)
    @user_owes = Register.current_user_owes(current_user.id)
    
    @unsorted_registers = @owes_user + @user_owes
    @registers = @unsorted_registers.sort_by {|item| item.updated_at}.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registers }
    end
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
    @register = Register.find(params[:id])

    if @register.creditor_id != current_user.id && @register.debtor_id != current_user.id
      flash[:error] = "You can't view a register for which you are not either the creditor or the debtor."
      begin
        redirect_to :back
      rescue Exception
        redirect_to summary_url
      end
    end 
  end

  def audit
    @register = Register.find(params[:id])

    @you_owe_me = YouOweMe.you_owe_me_audit(@register.creditor_id, @register.debtor_id) 
    
    @payment = Payment.payment_audit(@register.creditor_id, @register.debtor_id)
    
    @audit = Audit.audit_math(@you_owe_me, @payment)

    @records = @you_owe_me + @payment

    @sorted_records = @records.sort_by {|item| item.created_at}.reverse

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @register }
    end
  end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :creditor_id %><br />
    <%= f.number_field :creditor_id %>
  </div>
  <div class="field">
    <%= f.label :debtor_id %><br />
    <%= f.number_field :debtor_id %>
  </div>
  <div class="field">
    <%= f.label :credit_extended %><br />
    <%= f.number_field :credit_extended %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/audit.html.erb
<h1>Audit for Register <%= @register.id%></h1>
<div class="receipt_show">
  <p>
    <b>Id:</b>
    <%= @register.id %>
  </p>

  <p>
    <b>Creditor:</b>
    <%= User.find(@register.creditor_id).full_name %>
  </p>

  <p>
    <b>Debtor:</b>
    <%= User.find(@register.debtor_id).full_name %>
  </p>

  <p>
    <b>Credit extended:</b>
    <%= @register.credit_extended %>
  </p>

  <p>
    <b>Audit:</b>
    <%= @audit %>
  </p>

  <p>
    <b>Updated at:</b>
    <%= @register.updated_at %>
  </p>
</div>

<div class="container">
  <h1>Transactions on this Register</h1>
  <table class="table table-bordered dotmatrix-striped">
    <thead>
      <tr>
        <th>Id TESTING ONLY</th>
        <th>Date</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Creditor</th>
        <th>Debtor</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @sorted_records.each do |record| %>
        <tr>
          <td><%= record.id %></td>
          <td><%= record.created_at.to_date.to_formatted_s(:short) %></td>
          <% if record.respond_to?(:amount) %>
            <td><%= "Expense - #{Expense.find(record.expense_id).expense_name}"%></td>
            <td><%= record.amount %></td>
          <% end %>
          <% if record.respond_to?(:total_amount) %>
            <td><%= "Payment - From #{User.find(record.user_id).first_name} to #{User.find(record.receiver_id).first_name}" %></td>
            <td><%= record.total_amount*(-1) %></td>
          <% end %>
          <td><%= User.find(@register.creditor_id).full_name %></td>
          <td><%= User.find(@register.debtor_id).full_name %></td>
          <td><%= link_to 'Show', record %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Creditor</th>
    <th>Debtor</th>
    <th>Credit extended</th>
    <th>Updated at</th>
    <th></th>
  </tr>

<% @registers.each do |register| %>
  <tr>
    <td><%= register.id %></td>
    <td><%= register.creditor_id %></td>
    <td><%= register.debtor_id %></td>
    <td><%= register.credit_extended %></td>
    <td><%= register.updated_at %></td>
    <td><%= link_to 'Show', register %></td>
  </tr>
<% end %>
</table>
<br />

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<div class="receipt_show">
  <h2> <%= "Expense Between #{@register.creditor_id} and #{@register.debtor_id}" %> </h2>

  <p>
    <b>Id:</b>
    <%= @register.id %>
  </p>

  <p>
    <b>Creditor:</b>
    <%= @register.creditor_id %>
  </p>

  <p>
    <b>Debtor:</b>
    <%= @register.debtor_id %>
  </p>

  <p>
    <b>Credit extended:</b>
    <%= @register.credit_extended %>
  </p>

  <p>
    <b>Updated at:</b>
    <%= @register.updated_at %>
  </p>

  <div class="row-fluid">
    <%= link_to 'Audit', audit_register_path(@register), :class => "btn btn-warning pull-right" %>
  </div>

</div>