config/routes.rb
BillsWithFriends::Application.routes.draw do
  devise_for :users

  resources :users

  resources :registers

  resources :you_owe_mes

  resources :payments

  resources :expenses

  root :to => "home#index"

  match '/summary', :to => 'summary#index'

  match '/ledger', :to => 'ledger#index'

  match '/registers/:id/audit', :to => "registers#audit", :as => "audit_register"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

end

app/models/you_owe_me.rb
class YouOweMe < ActiveRecord::Base
	#Calls the update_register method before saving a you_owe_me
	before_create :add_you_owe_me_to_register
	before_update :update_register
	before_destroy :subtract_you_owe_me_from_register

	belongs_to :expense

	default_scope :order => 'created_at DESC'

	validates_presence_of :amount, :creditor_id, :debtor_id
	validates :amount, :numericality => {:greater_than_or_equal_to => 1}
	#Need to add a validation to ensure that you cannot submit a you_owe_me where the debtor and creditor ids are the same

	def self.you_owe_me_audit(creditor_id, debtor_id)
		where(:creditor_id => creditor_id, :debtor_id => debtor_id)
	end

	def self.that_belong_to_expense(expense_id)
		where(:expense_id => expense_id)
	end

	def self.user_is_debtor(debtor_id)
		where(:debtor_id => debtor_id)
	end

	private

	#This method creates a register if it doesn't exist and then adds the you_owe_me.amount to the register.credit_extended
  def add_you_owe_me_to_register
  	register = Register.where(:creditor_id => creditor_id, :debtor_id => debtor_id).first
  	register ||= Register.new(:creditor_id => creditor_id, :debtor_id => debtor_id)

    credit_extended = register.credit_extended + self.amount
    register.update_attributes(:credit_extended => credit_extended)
  end

  def update_register
  	register = Register.where(:creditor_id => creditor_id, :debtor_id => debtor_id).first

    credit_extended = register.credit_extended + (self.amount - self.amount_was)
    register.update_attributes(:credit_extended => credit_extended)
  end

  def subtract_you_owe_me_from_register
  	register = Register.where(:creditor_id => creditor_id, :debtor_id => debtor_id).first

    credit_extended = register.credit_extended - self.amount
    register.update_attributes(:credit_extended => credit_extended)
  end
end

app/controllers/you_owe_mes_controller.rb
class YouOweMesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /you_owe_mes
  # GET /you_owe_mes.json
  def index
    @you_owe_mes = YouOweMe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @you_owe_mes }
    end
  end

  # GET /you_owe_mes/1
  # GET /you_owe_mes/1.json
  def show
    @you_owe_me = YouOweMe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @you_owe_me }
    end
  end

  # GET /you_owe_mes/new
  # GET /you_owe_mes/new.json
  def new
    @you_owe_me = YouOweMe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @you_owe_me }
    end
  end

  # GET /you_owe_mes/1/edit
  #def edit
    #@you_owe_me = YouOweMe.find(params[:id])

     #if @you_owe_me.creditor_id != current_user.id
      #flash[:error] = "You can't edit a debt that you didn't create."
      #redirect_to @you_owe_me
    #end 
  #end

  # POST /you_owe_mes
  # POST /you_owe_mes.json
  def create
    @you_owe_me = YouOweMe.new(params[:you_owe_me])

    respond_to do |format|
      if @you_owe_me.save
        format.html { redirect_to @you_owe_me, notice: 'You owe me was successfully created.' }
        format.json { render json: @you_owe_me, status: :created, location: @you_owe_me }
      else
        format.html { render action: "new" }
        format.json { render json: @you_owe_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /you_owe_mes/1
  # PUT /you_owe_mes/1.json
  def update
    @you_owe_me = YouOweMe.find(params[:id])

    if @you_owe_me.creditor_id == current_user.id
      if @you_owe_me.update_attributes(params[:you_owe_me])
        flash[:success] = 'Debt was successfully updated.'
      else
        render action: "edit"
      end
    else
      flash[:error] = "You can't update a debt that you didn't create."
    end

    redirect_to @you_owe_me
  end

  # DELETE /you_owe_mes/1
  # DELETE /you_owe_mes/1.json
  #def destroy
    #@you_owe_me = YouOweMe.find(params[:id])
    
    #if @you_owe_me.creditor_id == current_user.id
      #@you_owe_me.destroy
      #flash[:success] = "You have successfully deleted the debt."
    #else
      #flash[:error] = "You can't delete debts that you didn't create."
    #end

    #redirect_to you_owe_me_url
  #end
end

app/helpers/you_owe_mes_helper.rb
module YouOweMesHelper
end

app/views/you_owe_mes/_form.html.erb
<%= form_for(@you_owe_me) do |f| %>
  <% if @you_owe_me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@you_owe_me.errors.count, "error") %> prohibited this you_owe_me from being saved:</h2>

      <ul>
      <% @you_owe_me.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :expense_id %><br />
    <%= f.number_field :expense_id %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :creditor_id %><br />
    <%= f.number_field :creditor_id %>
  </div>
  <div class="field">
    <%= f.label :debtor_id %><br />
    <%= f.number_field :debtor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/you_owe_mes/index.html.erb
<h1>Listing you_owe_mes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Expense</th>
    <th>Created at</th>
    <th>Amount</th>
    <th>Creditor</th>
    <th>Debtor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @you_owe_mes.each do |you_owe_me| %>
  <tr>
    <td><%= you_owe_me.id %></td>
    <td><%= you_owe_me.expense_id %></td>
    <td><%= you_owe_me.created_at %></td>
    <td><%= you_owe_me.amount %></td>
    <td><%= you_owe_me.creditor_id %></td>
    <td><%= you_owe_me.debtor_id %></td>
    <td><%= link_to 'Show', you_owe_me %></td>
    <td><%= edit_decider(you_owe_me) %></td>
    <td><%= destroy_decider(you_owe_me) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New You owe me', new_you_owe_me_path %>

app/views/you_owe_mes/new.html.erb
<h1>New you_owe_me</h1>

<%= render 'form' %>

<%= link_to 'Back', you_owe_mes_path %>

app/views/you_owe_mes/show.html.erb
<div class="receipt_show">
  <h2> You Owe Me - Debit </h2>
  <p>
    <b>Id:</b>
    <%= @you_owe_me.id %>
  </p>

  <p>
    <b>Expense:</b>
    <%= @you_owe_me.expense_id %>
  </p>

  <p>
    <b>Created at:</b>
    <%= @you_owe_me.created_at %>
  </p>

  <p>
    <b>Amount:</b>
    <%= @you_owe_me.amount %>
  </p>

  <p>
    <b>Creditor:</b>
    <%= @you_owe_me.creditor_id %>
  </p>

  <p>
    <b>Debtor:</b>
    <%= @you_owe_me.debtor_id %>
  </p>
</div>