config/routes.rb
BillsWithFriends::Application.routes.draw do
  devise_for :users

  resources :users

  resources :registers

  resources :you_owe_mes

  resources :payments

  resources :expenses

  root :to => "home#index"

  match '/summary', :to => 'summary#index'

  match '/ledger', :to => 'ledger#index'

  match '/registers/:id/audit', :to => "registers#audit", :as => "audit_register"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	#Calls the update_register method before saving a payment
	before_create :subtract_payment_from_register
	before_update :update_register
	before_destroy :add_payment_to_register

	belongs_to :user
	
	default_scope :order => 'created_at DESC'

	validates_presence_of :user_id, :date_paid, :total_amount, :receiver_id
	validates :total_amount, :numericality => {:greater_than_or_equal_to => 1}
	validates_with PaymentValidator

	def self.payment_audit(creditor_id, debtor_id)
		where(:receiver_id => creditor_id, :user_id => debtor_id)
	end

  def self.user_is_receiver(current_user_id)
    where(:receiver_id => current_user_id)
  end

	private

	#This method subtracts the payment.amount to the register.credit_extended
  def subtract_payment_from_register
  	register = Register.where(:creditor_id => receiver_id, :debtor_id => user_id).first
  	
    credit_extended = register.credit_extended - self.total_amount
    register.update_attributes(:credit_extended => credit_extended)
  end

   def update_register
  	register = Register.where(:creditor_id => receiver_id, :debtor_id => user_id).first
    
    credit_extended = register.credit_extended - (self.total_amount - self.total_amount_was)
   	register.update_attributes(:credit_extended => credit_extended)	
  end

  def add_payment_to_register
  	register = Register.where(:creditor_id => receiver_id, :debtor_id => user_id).first
    
    credit_extended = register.credit_extended + self.total_amount
   	register.update_attributes(:credit_extended => credit_extended)	
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new
    @previous_payments = current_user.payments
    @users = User.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
    @users = User.all

    if @payment.user_id != current_user.id
      flash[:error] = "You can't edit a payment that you didn't create."
      redirect_to @payment
    end 
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])
    @previous_payments = current_user.payments
    @users = User.all

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    if @payment.user_id == current_user.id
      if @payment.update_attributes(params[:payment])
        flash[:success] = 'Payment was successfully updated.'
      else
        render action: "edit"
      end
    else
      flash[:error] = "You can't update a payment that you didn't create."
    end

    redirect_to @payment
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    
    if @payment.user_id == current_user.id
      @payment.destroy
      flash[:success] = "You have successfully deleted the payment."
    else
      flash[:error] = "You can't delete payments that you didn't create."
    end

    redirect_to payments_url
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<% if @payment.errors.any? %>
  <div id="error_explanation" class="alert alert-error">
    <% @payment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>
    
<div class="check">
  <%= simple_form_for @payment do |f| %>
    <%= f.hidden_field :id -%>
    <%= f.hidden_field :user_id, :value => current_user.id -%>
    <%= f.hidden_field :created_at -%>

    <div class="row-fluid">
      <div class="span6">
        <%= current_user.full_name-%>
      </div>
      <div class="span6 pull-right">
        <%= "1234"-%>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12 pull-right">
        <%= f.input :date_paid, :as => :date, :default => 1.day.ago, :input_html => { :class => 'input-small' }-%>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span6">
        <%= f.input :receiver_id, :label => 'Who Was Paid', :collection => @users, :label_method => :drop_down_display, :value_method => :id-%>
      </div>
      <div class="span2">
        <%= f.input :total_amount, :label => '$'%>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <%= "$ Dollars" -%>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6 pull-left">
        <%= f.input :memo-%>
      </div>
      <div class="span6 pull-right">
        <%= f.button :submit, :class => 'btn-success' -%>
      </div> 
    </div> 
  <% end %>
</div>

app/views/payments/_index.html.erb
<h1>Payments that You've Created</h1>

<table class="table table-bordered dotmatrix-striped">
  <thead>
      <tr>
        <th>Id</th>
        <th>Owner</th>
        <th>Receiver</th>
        <th>Date paid</th>
        <th>Created at</th>
        <th>Total amount</th>
        <th>Memo</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
  </thead>
  <tbody>
    <% @previous_payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= User.find(payment.user_id).full_name %></td>
        <td><%= User.find(payment.receiver_id).full_name %></td>
        <td><%= payment.date_paid.to_date.to_formatted_s(:long) %></td>
        <td><%= payment.created_at.to_date.to_formatted_s(:long)  %></td>
        <td><%= "$#{payment.total_amount}" %></td>
        <td><%= payment.memo %></td>
        <td><%= link_to tag("i", :class => 'icon-eye-open'), payment %></td>
        <td><%= edit_decider(payment) %></td>
        <td><%= destroy_decider(payment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

app/views/payments/index.html.erb
<h1>Listing Payments</h1>
<table class="table table-bordered dotmatrix-striped">
  <thead class="dotmatrix-striped">
    <tr>
      <th>Id</th>
      <th>Owner</th>
      <th>Receiver</th>
      <th>Date paid</th>
      <th>Created at</th>
      <th>Total amount</th>
      <th>Memo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= payment.user_id %></td>
        <td><%= payment.receiver_id %></td>
        <td><%= payment.date_paid %></td>
        <td><%= payment.created_at %></td>
        <td><%= payment.total_amount %></td>
        <td><%= payment.memo %></td>
        <td><%= link_to tag("i", :class => 'icon-eye-open'), payment %></td>
        <td><%= edit_decider(payment) %></td>
        <td><%= destroy_decider(payment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Payment', new_payment_path, :class => "btn btn-success" %>

app/views/payments/new.html.erb
<div class="container">
	<h1>Record a Payment</h1>
		<%= render 'form' %>
		<%= render 'index' %>
</div>

app/views/payments/show.html.erb
<div class="check">
 
  <div class="row-fluid">
    <div class="span6">
      <%= User.find(@payment.user_id).full_name.capitalize -%>
    </div>
    <div class="span6 pull-right">
      <%= "1234"-%>
    </div>
  </div>
  <div class="row-fluid underline">
    <div class="span12 pull-right">
      <%= "Date: #{@payment.date_paid.to_date.to_formatted_s(:long)}" -%>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6 underline">
      <%= "Receiver: #{User.find(@payment.receiver_id).full_name.capitalize}" -%>
    </div>
    <div class="span6 pull-right">
      <%= "$ #{@payment.total_amount}" -%>
    </div>
  </div>
    
  <div class="row-fluid">
    <div class="span12  underline">
      <%= " #{@payment.total_amount} Dollars" -%>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span6 underline">
      <%= "Memo: #{@payment.memo}" %>
    </div>
    <div class="span6">
      <div class="actions span6 pull-right">
        <%= User.find(@payment.user_id).full_name.capitalize-%>
      </div>
    </div>  
  </div>
  <div class="row-fluid">
    <%= link_to 'Edit', edit_payment_path(@payment), :class => "btn btn-primary pull-right" %>
  </div>
</div>
 